name: "PR Checks"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
        
    - name: "check for uncommitted changes"
      run: |
        git diff --exit-code --stat -- . ':!node_modules' || \
        (echo "##[error] found changed files after build. please run 'npm run format && npm run build' and check in all changes." && \
        exit 1)